import LocalizationString from 'react-localization';

let translation = new LocalizationString<any>({
  en: {
    hello: 'Hello Pepsi',
    generalError: 'Error Occurred',
    home: 'Home',
    register: 'Register',
    login: 'Login',
    loading: 'Loading....',
    firstName: 'First name',
    lastName: 'Last Name',
    password: 'Password',
    mobileNumber: 'Mobile Number',
    loginSub: 'Please enter you account info',
    about: 'About',
    useCode: 'Using the code',
    enterCode: 'Enter the code',
    terms: 'Terms and Conditions',
    faq: 'FAQ',
    pepsiGifts: 'Pepsi gifts',
    aboutProgram: 'About the program',
    readMoreAboutPepsiGifts: 'Read more about the Pepsi Gifts program',
    registerMain: 'Register for a new account',
    registerSub: 'Please enter your personal data',
    registerBtn: 'COMPLETE REGISTRATION',
    email: 'Email Address:',
    confirmPassword: 'Re-enter password:',
    codeArtwork: ' Your code is under this lid',
    insertCodeText: 'Insert the code under the Pepsi can lid to get your instant gift now',
    insertCode: 'Insert the code',
    insertCodeHere: 'Enter the code here',
    sendCode: 'Send code',
    currentLevel: 'Current level',
    currentLevelText:
      'You are currently on the third level and you have a gift that you can enjoy now or wait for the next level with a bigger gift',
    discount: 'Discount from the Pepsi App',
    thisOfferAvailable: 'This offer is now available for you',
    congratulationsPepsi: 'Congrats, you won',
    giftCode: 'Gift code',
    howCode: 'How to use the code',
    codeCashier:
      'Please write the code and display it for the cashier in the restaurant to take advantage of the gift',
    termsConditionsApply: 'Terms and conditions apply',
    accountSuccess: 'Your account has been created successfully!',
    giftsHistory: 'Gifts History',
    giftsHistoryListText: 'This list is for gifts you previously won.',
    notUsed: 'Not used yet',
    used: 'Used',
    gift: 'The gift',
    dateTime: 'Date and time',
    couponNumber: 'Coupon number',
    expireDate: 'Expiry date',
    status: 'Status',
    getOffer: 'Get the offer',
    invalidMail: 'Invalid Email',
    requiredField: 'Field is required',
    invalidPassword: 'Invalid password',
    invalidMobileNumber: 'Invalid mobile number',
    requiredFirstName: 'Please enter first name',
    requiredLastName: 'Please enter last name',
    requiredPassword: 'Please enter Password',
    requiredConfirmPassword: 'Please enter confirm password',
    requiredEmail: 'Please enter email',
    requiredMobileNumber: 'Please enter Mobile number',
    wrongAuth: 'Wrong mobile number or password',
    registerLanguage: 'Select Language',
    continue: 'Continue',
    languageSub: 'please choose your preferred language',
    haveAccount: 'Have an account?',
    donthaveAccount: "Don't have an account?",
    logout: 'Sign out',
    unExpectedError: 'Unexpected Error',
    pepsiGifts20: 'Pepsi Prizes 2020',
    copyRights: 'All rights reserved',
    howParticipate: 'How to participate',
    lookCodeCover: 'Look for the code under the lid',
    insertCodeOn: 'Insert code on pepsiprize.com',
    whenYouInsertCodeWin:
      'Win instantly and collect more cans to win bigger gifts',
    gifts: 'Gifts',
    aboutItem1:
      'When you collect 1 can, you immediately win a free twister with any medium combo from KFC (instore & Call Center)',
    aboutItem1_1: 'Twister sandwich with any medium combo in KFC store',
    aboutItem1_2: '20% discount on KFC order through the app',
    aboutItem2: 'When you collect two cans, you get 20% off any order on Pepsi',
    aboutItem3: 'When you collect 3 cans, you can win one of the following gifts:',
    aboutItem3_1: 'Free Zinger with any Medium Combo from KFC (instore & Call Center)',
    aboutItem3_2: 'Or 20% off on KFC delivery App (capped at 10 SR) from KFC',
    aboutItem4: 'When you collect 6 cans, you can win one of the following gifts:',
    aboutItem4_1: '1 month free subscription on StarzPlay',
    aboutItem4_2: 'Or 1 month free subscription on Shahid VIP',
    aboutItem4_3: 'Or 1 month free subscription on Anghami Plus',
    aboutItem4_4:
      'Or a Free Snack Box from KFC (instore & Call Center) + add 10 SAR to upgrade to Super Dinner (4pc Meal)',
    aboutItem4_5: 'Or a 30% discount form KFC delivery app',
    aboutItem5: 'When you collect 10 cans, you win 1 Vox standard cinema ticket',
    aboutItem6: 'Important information about gifts and offers',
    aboutItem6_1: 'This offer is valid for Pepsi Can 240ml, 330ml, 355ml, 320ml and 360ml',
    aboutItem0_1:
      'Register on the website to automatically enroll to the weekly raffle draw. The more codes you enter, the higher chances of winning SR3000 voucher from eXtra store',
    aboutItem6_3: 'End date of campaign is 17 Oct and last day of redemption is 31 Oct',
    howToUseGifts: 'How to get your reward',
    codeExistUnderCan: 'Code can be found under the can lid',
    enterPrintedCode: 'Enter the printed code & press on send code',
    newCodeAddedToAccount: 'New code has been added to your account',
    noHistory: 'No History',
    forgetText1: 'Forgot your password?',
    forgetText2: 'Click here to reset it',
    footerText:
      ' If you already have an account with Pepsi Awards, click on Register or create your account again',
    footerSubscriptionsText: 'Control the email and text activation service',
    subscriptions: 'Activate subscriptions',
    subscriptionControl: 'Subscription control',
    subscriptionsModal:
      'Through the window you can activate / deactivate the subscription service in e-mail and text messages. Select / deselect your choice',
    saveSettings: 'Save the settings',
    subscriptionMail: 'Activate email subscription',
    regTerms: 'I agree on the terms and conditions',
    subscriptionMgs: 'Activate text message subscription',
    otpText: 'Please check your email and enter the verification code we sent you below',
    otpTextMail: "If you didn't find the email,Please check the junk E-mail",
    identityVerification: 'Identity verification',
    passwordSuccessText: 'Password changed successfully',
    forgetPassword: 'Forgot Password ?',
    forgetPasswordSub:
      'Please enter your registered Email and follow the istructions to reset password',
    changePassword: 'Change Password',
    newPassword: 'Enter the new password below',
    noOffers: 'There are no offers',
    nextLevel: 'To reach the next level',
    collect: 'You have ',
    toCollect: 'Collect',
    cans: 'cans',
    youCollect: 'You have collected',
    deserveGift: 'Choose one of the following gifts',
    canSubstitute: 'You can substitute',
    codesNow: 'codes now',
    otherCans: 'Other cans to win a bigger gift',
    orCollect: 'or collect cans',
    waitCollect: 'Wait and collect more cans',
    gift1Details:
      'Your account has been created successfully. You are now eligible for a weekly raffle for a chance to win a 3000 SR voucher from extra',
    tryAgainLater: 'Please try later.',
    privacy: 'Privacy Policy',
    privacyHeading: 'PEPSICO MIDDLE EAST & NORTH AFRICA PRIVACY POLICY',
    clickToLogin: 'Have an account with us?',
    accountWithUs: 'Click to log in',
    termsHeading: 'The terms and conditions for the Campaign',
    aboutPepsiAwards: 'About the Pepsi Awards',
    aboutPepsiAwardsText: 'Learn more about the valuable Pepsi gifts you earn with collecting',
    cansNumber: 'Number of cans collected',
    merchantLogo: 'Merchant logo',
    collect1: 'Collect one can',
    collect2: 'Collect two can',
    collect3: 'Collect 3 cans',
    collect6: 'Collect 6 cans',
    collect10: 'Collect 10 cans',
    giftDetail1: 'Free Zinger with any Medium Combo from KFC (instore & CC)',
    giftDetail2: '20% discount on KFC order through the app',
    giftDetail3: '20% discount on any order from the Pepsi app',
    giftDetail4: 'Free KFC Zinger in store',
    giftDetail5: ' 30% discount on any order from the Kentucky Fried Chicken app',
    giftDetail6: 'Discounts from Kentucky Fried Chicken, Shahid, Anghami and STARZPLAY',
    giftDetail7: '1 Vox standard cinema ticket',
    close: 'Finish',
    knowMoreGifts: 'Learn more about the awards',
    greatGift: 'The great gift',
    tierDescription:
      ' cans and you can select one of the below prizes or collect more to win more prizes',
    artWorkCan: 'Pepsi can',
    artWorkCode: 'Vouhcer code',
    congratulationsYouWin: 'Congratulations you also won',
  },
  ar: {
    hello: 'مرحبا بيبسي',
    generalError: 'حدث خطا',
    home: 'اكسب مع بيبسي',
    register: 'انشاء حساب',
    login: 'تسجيل الدخول',
    loading: ' ....جارى التحميل',
    firstName: 'اسم المستخدم',
    lastName: 'اسم العائلة',
    password: 'كلمة المرور',
    mobileNumber: 'رقم الموبايل',
    loginSub: 'ادخل بياناتك للدخول على حسابك الخاص',
    about: 'عن البرنامج',
    useCode: 'استخدام الرمز',
    enterCode: 'ادخال الرمز',
    terms: 'الشروط والأحكام',
    faq: 'الأسئلة المتكررة',
    pepsiGifts: 'هدايا بيبسي',
    aboutProgram: 'عن البرنامج',
    readMoreAboutPepsiGifts: 'اقرأ المزيد عن برنامج هدايا بيبسي',
    registerMain: 'انشاء حساب',
    registerSub: 'ادخل بياناتك لإنشاء حساب جديد',
    registerBtn: 'انشاء حساب جديد',
    email: 'البريد الإلكتروني:',
    confirmPassword: 'اعد كتابة كلمة المرور',
    codeArtwork: ' الرمز الخاص بك تحت هذا الغطاء',
    insertCodeText: 'قم بإدخال الرمز الموجود على غطاء عبوة بيبسي لتحصل على هديتك الفورية الآن',
    insertCode: 'ادخل الرمز',
    insertCodeHere: 'ادخل الرمز هنا',
    sendCode: 'ارسال الرمز',
    currentLevel: 'المستوى الحالي',
    currentLevelText:
      'انت حاليا في المستوى الثالث ولديك هدية يمكنك الاستمتاع بها الآن او انتظر للمستوى القادم بهدية اكبر',
    discount: 'خصم من تطبيق بيبسي',
    thisOfferAvailable: 'هذا العرض اصبح متاحا لك',
    getOffer: 'احصل على العرض',
    invalidMail: 'البريد الالكترونى غير صحيح',
    requiredField: 'ادخل بيانات صحيحة',
    invalidPassword: 'من فضلك ادخل كلمة مرور صحيحة',
    invalidMobileNumber: 'من فضلك ادخل رقم جوال صحيح',
    requiredFirstName: 'من فضلك ادخل اسم المستخدم',
    requiredLastName: 'من فضلك ادخل اسم العائلة',
    requiredPassword: 'من فضلك ادخل كلمة المرور',
    requiredConfirmPassword: 'من فضلك ادخل تاكيد كلمة المرور',
    requiredEmail: 'من فضلك ادخل البريد الالكترونى',
    requiredMobileNumber: 'من فضلك ادخل رقم الجوال',
    wrongAuth: 'رقم الجوال او كلمة المرور غير صحيحة',
    congratulationsPepsi: 'مبروك ربحت',
    giftCode: 'الرمز',
    howCode: 'طريقة استخدام الرمز',
    codeCashier: 'برجاء كتابة الرمز واظهاره للكاشير في المطعم للإستفاده من الهدية',
    termsConditionsApply: 'تطبق الشروط والأحكام',
    accountSuccess: 'تم انشاء حسابك بنجاح!',
    giftsHistory: 'سجل الهدايا',
    giftsHistoryListText: 'هذه القائمة خاصة بالهدايا التي ربحتها سابقا.',
    notUsed: 'لم يستخدم بعد',
    used: 'مستخدم',
    gift: 'الهدية',
    dateTime: 'التاريخ والوقت',
    couponNumber: 'رقم الكوبون',
    expireDate: 'تاريخ الانتهاء',
    status: 'الحالة',
    registerLanguage: 'اختر اللغة',
    continue: 'استمرار',
    languageSub: 'من فضلك اختر لغتك المفضلة',
    haveAccount: 'لديك حساب؟',
    donthaveAccount: 'ليس لديك حساب؟',
    logout: 'تسجيل الخروج',
    unExpectedError: 'حدث خطا بالنظام..',
    pepsiGifts20: 'جوائز بيبسي ٢٠٢٠',
    copyRights: 'جميع الحقوق محفوظه',
    howParticipate: 'كيفية المشاركة',
    lookCodeCover: 'ابحث عن الرمز تحت غطاء العلبة',
    insertCodeOn: 'أدخل الرمز على pepsiprize.com',
    whenYouInsertCodeWin:
      'عند إدخال الرمز تربح هدية فورية و عند التجميع تزيد فرصة الفوز بهدايا أكثر',
    gifts: 'الهدايا',
    aboutItem1:
      'عند تجميع عبوة واحدة تكسب على الفور سندويش تويستر مجاناً مع أي كومبو متوسط من أحد فروع KFC أو عن طريق خدمة التوصيل',
    aboutItem1_1: 'ساندويتش تويستر مع أي كومبو متوسط ​​في متجر دجاج كنتاكي',
    aboutItem1_2: 'خصم 20٪ على طلب كنتاكي من خلال التطبيق',
    aboutItem2: 'عند تجميع عبوتين تحصل على خصم 20٪ من أي طلب على تطبيق بيبسي',
    aboutItem3: 'عند تجميع 3 عبوات، تربح من KFC أحد الخيارات التالية:',
    aboutItem3_1: 'زنجر مجاني في متجر KFC أو عن طريق خدمة التوصيل',
    aboutItem3_2: 'أو 20% من تطبيق  KFC',
    aboutItem4: 'عند تجميع 6 عبوات، تربح أحد الخيارات التالية:',
    aboutItem4_1: 'اشتراك شهر واحد من StarzPlay',
    aboutItem4_2: '  اشتراك شهر واحد من أنغامي بلس',
    aboutItem4_3: 'أو اشتراك شهر واحد من شاهد  VIP',
    aboutItem4_4:
      ' أو وجبة سناك بوكس مجانية من أحد فروع KFC  عن طريق خدمة التوصيل (أضف 10 ريال لتحصل على وجبة سوبر دينر)',
    aboutItem4_5: ' أو خصم 30% من تطبيق KFC',
    aboutItem5: 'عند تجميع 10 عبوات ، تربح تذكرة سينما VOX مجانية',
    aboutItem6: 'معلومات هامة عن الهدايا والعروض',
    aboutItem6_1: 'هذا العرض ساري على عبوة بيبسي 240 مل 330 مل، 355 مل، 320 مل، 360 مل',
    aboutItem0_1:
      'سجل على الموقع للدخول في السحب تلقائيًا. كلما زاد عدد الرموز التي أدخلتها، زادت فرصة الفوز بكوبون من متجر اكسترا بقيمة 3000 ريال',
    aboutItem6_3: 'ينتهي العرض في 17 اكتوبر و اخر يوم لاسترداد الجوائز 31 اكتوبر',
    howToUseGifts: 'كيفية استخدام الجوائز',
    codeExistUnderCan: 'يوجد رمز مطبوع تحت غطاء العبوة',
    enterPrintedCode: 'أدخل الرمز المطبوع و إضغط على زر إرسال الرمز',
    newCodeAddedToAccount: 'تم إضافة الرمز الجديد إلى حسابك',
    noHistory: 'لايوجد سجل للهدايا',
    forgetText1: 'نسيت كلمة المرور؟',
    forgetText2: 'اضغط هنا لإعادة تعيينها',
    footerText:
      'اذا كان لديك حساب بالفعل على جوائز بيبسي قم بالضغط على تسجيل.او انشىْ حسابك من جديد',
    footerSubscriptionsText: ' قم بالتحكم فى خدمة تفعيل البريد الالكترونى والرسائل النصية',
    subscriptions: 'تفعيل الاشتراكات',
    subscriptionControl: 'التحكم فى الاشتراك',
    subscriptionsModal:
      'من خلال النافذة يمكنك تفعيل/الغاء تفعيل خدمة الاشتراك فى البريد الالكترونى والرسائل النصية.قم بتحديد/الغاء تحديد اختيارك',
    saveSettings: 'حفظ الاعدادات',
    subscriptionMail: 'تفعيل اشتراك البريد الالكترونى',
    regTerms: 'أوافق على الشروط والأحكام',
    subscriptionMgs: 'تفعيل اشتراك الرسائل النصية',
    otpText: 'من فضلك تفقد بريدك الإلكتروني وقم بإدخال رمز التحقق الذي ارسلناه لك بالأسفل',
    otpTextMail: "إذا لم تجد البريد الإلكتروني ، يرجى التحقق من مجلد الاسبام",
    identityVerification: 'التحقق من الهوية',
    passwordSuccessText: 'تم تغيير كلمة المرور بنجاح',
    forgetPassword: 'نسيت كلمة المرور؟',
    forgetPasswordSub:
      'من فضلك ادخل عنوان البريد الإلكتروني المسجل واتبع التعلىمات لإعادة تعيين كلمة المرور',
    changePassword: 'تغيير كلمة المرور',
    newPassword: 'قم بإدخال كلمة المرور الجديدة بالأسفل',
    noOffers: ' لايوجد عروض',
    nextLevel: 'للوصول للمستوى التالى',
    collect: ' جمعت',
    toCollect: 'جمع',
    cans: 'عبوات',
    youCollect: 'لقد جمعت',
    deserveGift: 'اختار احدى الهدايا التالية',
    canSubstitute: 'يمكنك استبدال',
    codesNow: 'اكواد الآن',
    otherCans: 'عبوات اخري للفوز بهدية اكبر',
    orCollect: 'او تجميع ',
    waitCollect: 'انتظر و جمع اكثر',
    gift1Details:
      'تم انشاء حسابك بنجاح، وانت الآن مؤهل للفوز بالسحب الإسبوعي لفرصة الفوز بقسيمة شراء بقيمة 3000 ريال من اكسترا',
    tryAgainLater: 'حاول فى وقت لاحق',
    privacy: 'سياسة الخصوصية',
    privacyHeading: 'PEPSICO MIDDLE EAST & NORTH AFRICA PRIVACY POLICY',
    clickToLogin: 'اضغط لتسجيل الدخول',
    accountWithUs: 'لديك حساب معنا؟',
    termsHeading: 'شروط واحكام الحملة الترويجية',
    aboutPepsiAwards: 'عن جوائز بيبسي',
    aboutPepsiAwardsText: 'اعرف اكثر عن هدايا بيسي القيمة التي تربحها مع التجميع',
    cansNumber: 'عدد العبوات المجمعة',
    merchantLogo: 'شعار التاجر',
    collect1: 'تجميع عبوة واحدة',
    collect2: 'تجميع عبوتين',
    collect3: 'تجميع 3 عبوات',
    collect6: 'تجميع 6 عبوات',
    collect10: 'تجميع 10 عبوات',
    giftDetail1: 'سندويش تويستر مجاناً مع أي كومبو متوسط من أحد فروع KFC أو عن طريق خدمة التوصيل',
    giftDetail2: 'خصم 20٪ على طلب كنتاكي من خلال التطبيق',
    giftDetail3: 'خصم 20% على اي طلب من تطبيق بيبسي',
    giftDetail4: 'زنجر مجاني من دجاج كنتاكي في المتجر',
    giftDetail5: 'خصم 30٪ على أي طلب من تطبيق دجاج كنتاكي',
    giftDetail6: 'خصومات من دجاج كنتاكي، شاهد، انغامي وستارز بلاي',
    giftDetail7: 'تذكرة سينما VOX مجانية',
    close: 'انهاء',
    knowMoreGifts: 'اعرف اكتر عن الجوائز',
    greatGift: 'الهدية الكبرى',
    tierDescription: ' عبوات يمكنك الفوز بالجوائز التالية أو اجمع أكثر للفوز بجوائز أكبر ',
    artWorkCan: 'علبة بيبسي',
    artWorkCode: 'رمز الهدية',
    congratulationsYouWin: 'مبروك لقد ربحت ايضا مع كل عبوة',
  },
});

export default translation;
